apiVersion: v1
kind: Namespace
metadata:
  labels:
    control-plane: logs-exporter
  name: system
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: controller-manager
  namespace: system
  labels:
    control-plane: logs-exporter
spec:
  selector:
    matchLabels:
      control-plane: logs-exporter
  replicas: 1
  template:
    metadata:
      labels:
        control-plane: logs-exporter
    spec:
      containers:
        - image: controller:latest
          name: manager
          resources:
            limits:
              cpu: 100m
              memory: 30Mi
            requests:
              cpu: 100m
              memory: 20Mi
          env:
            - name: ELASTIC_USERNAME
              valueFrom:
                secretKeyRef:
                  name: logs-exporter-elastic
                  key: username
            - name: ELASTIC_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: logs-exporter-elastic
                  key: password
            - name: ELASTIC_URL
              valueFrom:
                secretKeyRef:
                  name: logs-exporter-elastic
                  key: url
            - name: ELASTIC_HOST
              valueFrom:
                secretKeyRef:
                  name: logs-exporter-elastic
                  key: host
      terminationGracePeriodSeconds: 10
      serviceAccount: logs-exporter-manager
